apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m08chzc0u-java-quarkus
  janus-idp.io/tekton: m08chzc0u-java-quarkus
  backstage.io/kubernetes-id: m08chzc0u-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: m08chzc0u-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
